blank_issues_enabled: false
contact_links:
  - name: ncSender Discussions
    url: https://github.com/siganberg/ncSender/discussions
    about: Ask questions, share ideas, and get community support here before filing an issue.
