name: Build Linux ARM64 Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux-arm64:
    name: Linux ARM64 (Raspberry Pi)
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # electron-builder is happier with this
      USE_SYSTEM_FPM: "true"                  # use system fpm we install below

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies (AppImage + .deb)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libfuse2 \
            rpm \
            fakeroot \
            ruby \
            ruby-dev \
            rubygems \
            build-essential
          sudo gem install --no-document fpm

      - name: Install JS deps
        run: |
          npm ci
          cd client && npm ci
        working-directory: app

      - name: Build client
        run: npm run build:client
        working-directory: app

      - name: Build Electron (Linux ARM64)
        run: |
          rm -rf dist-electron
          npm run dist -- --linux --arm64 --publish never
        working-directory: app

      - name: List artifacts
        run: ls -lh app/dist-electron/

      - name: Create/Update GitHub Release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body_path: latest_release.md
          files: |
            app/dist-electron/*.AppImage
            app/dist-electron/*.deb
            app/dist-electron/latest-linux*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
