name: Build Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  macos:
    name: macOS Builds
    runs-on: macos-14  # macOS Sonoma (stable)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm ci
          cd client && npm ci
        working-directory: app

      - name: Build Client
        run: npm run build:client
        working-directory: app

      - name: Build Electron (x64 + arm64)
        run: |
          rm -rf dist-electron
          npm run dist -- --mac --x64 --arm64 --publish never
        working-directory: app

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: app/dist-electron/**

  linux:
    name: Linux Builds
    runs-on: ubuntu-22.04  # Ubuntu 22.04 LTS (stable)
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm ci
          cd client && npm ci
        working-directory: app

      - name: Build Client
        run: npm run build:client
        working-directory: app

      - name: Build Electron (${{ matrix.arch }})
        run: |
          rm -rf dist-electron
          npm run dist -- --linux --${{ matrix.arch }} --publish never
        working-directory: app

      - name: Upload Linux Artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}-artifacts
          path: app/dist-electron/**

  windows:
    name: Windows Builds
    runs-on: windows-2022  # Windows Server 2022 (stable)
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm ci
          cd client && npm ci
        working-directory: app

      - name: Build Client
        run: npm run build:client
        working-directory: app

      - name: Build Electron (${{ matrix.arch }})
        shell: pwsh
        run: |
          if (Test-Path dist-electron) { Remove-Item dist-electron -Recurse -Force }
          npm run dist -- --win --${{ matrix.arch }} --publish never
        working-directory: app

      - name: Upload Windows Artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}-artifacts
          path: app/dist-electron/**

  raspberry-pi:
    name: Raspberry Pi Build
    runs-on: ubuntu-22.04  # Ubuntu 22.04 LTS (stable)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libfuse2 \
            rpm \
            fakeroot \
            ruby \
            ruby-dev \
            rubygems \
            build-essential
          sudo gem install --no-document fpm

      - name: Install Dependencies
        run: |
          npm ci
          cd client && npm ci
        working-directory: app

      - name: Build Client
        run: npm run build:client
        working-directory: app

      - name: Build Electron (Raspberry Pi ARM64)
        run: |
          rm -rf dist-electron
          npm run dist -- --linux --arm64 --publish never
        working-directory: app
        env:
          USE_SYSTEM_FPM: "true"

      - name: List built artifacts
        run: |
          echo "Built Raspberry Pi artifacts:"
          ls -lh app/dist-electron/

      - name: Upload Raspberry Pi Artifact
        uses: actions/upload-artifact@v4
        with:
          name: raspberry-pi-artifacts
          path: |
            app/dist-electron/*.deb
            app/dist-electron/*.AppImage

  release:
    name: Create Release
    needs: [macos, linux, windows, raspberry-pi]
    runs-on: ubuntu-22.04  # Ubuntu 22.04 LTS (stable)
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets (preserve electron-builder filenames)
        run: |
          mkdir -p release-assets
          TAG="${{ github.ref_name }}"

          echo "Downloaded artifacts structure:"
          find artifacts -type f

          copy_matching_files() {
            local source_dir="$1"
            shift
            if [ ! -d "$source_dir" ]; then
              return
            fi
            for pattern in "$@"; do
              find "$source_dir" -maxdepth 1 -type f -name "$pattern" -print -exec cp {} release-assets/ \;
            done
          }

          # macOS assets (keep default names for auto-updater compatibility)
          copy_matching_files "artifacts/macos-artifacts" "*.dmg" "*.pkg" "*.zip" "*.blockmap" "latest-mac.yml"

          # Windows assets
          copy_matching_files "artifacts/windows-x64-artifacts" "*.exe" "*.msi" "*.zip" "*.blockmap" "latest.yml"

          # Linux assets
          copy_matching_files "artifacts/linux-x64-artifacts" "*.AppImage" "*.deb" "*.rpm" "*.tar.gz" "latest-linux.yml"

          # Raspberry Pi assets
          copy_matching_files "artifacts/raspberry-pi-artifacts" "*.AppImage" "*.deb"

          echo "Release assets to upload:"
          ls -lh release-assets/

      - name: Checkout (for tag annotation)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get tag annotation
        id: tag_annotation
        run: |
          TAG="${{ github.ref_name }}"

          # Get the tag annotation (release notes)
          TAG_MESSAGE=$(git tag -l --format='%(contents)' "$TAG")

          # Save to file for use in release
          echo "$TAG_MESSAGE" > release-notes.md

          echo "Release notes:"
          cat release-notes.md

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --repo ${{ github.repository }} \
            --title "Release ${{ github.ref_name }}" \
            --notes-file release-notes.md \
            release-assets/*
